### ISSUE TITLE
Error: The getter 'JSON' isn't defined for the class '#lib1::ThemeService

### ISSUE THREAD

**Issue by ryanhz** [rxlabz/panache#1]
compiler message: file:///Users/Ryan/Applications/flutter/.pub-cache/git/flutterial_components-987e83ceb2328f5400991a50b7a476d48e5e3e5d/lib/src/theme_service.dart:34:22: Error: Getter not found: 'JSON'.
compiler message:     final themeMap = JSON.decode(jsonTheme);
compiler message:                      ^^^^
compiler message: file:///Users/Ryan/Applications/flutter/.pub-cache/git/flutterial_components-987e83ceb2328f5400991a50b7a476d48e5e3e5d/lib/src/theme_service.dart:34:22: Error: The getter 'JSON' isn't defined for the class '#lib1::ThemeService'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'JSON'.
compiler message:     final themeMap = JSON.decode(jsonTheme);

**Comment by rxlabz** [comment]
Thanks ! ( and sorry for the delay ). the Json export/import is deactivated for now and will be reimplemented. I close this.
