### ISSUE TITLE
Adjusting the first in-app slider crashes the app

### ISSUE THREAD

**Issue by rhalff** [rxlabz/panache#14]
Adjusting the first slider crashes the app, the other sliders do not seem to show this behavior.

<img src="https://user-images.githubusercontent.com/274358/64348145-f885d100-cff4-11e9-82ec-235f7c7a3926.png" width="50%"/>

---

<img src="https://user-images.githubusercontent.com/274358/64348135-f4f24a00-cff4-11e9-8ef2-e67d115028bf.png" width="50%"/>

**Comment by rxlabz** [comment]
thanks ! It's strange, this bug only appears in release mode... I'll investigate.

**Comment by rxlabz** [comment]
Thanks again for reporting for now in the browser the slider crash if he has a valueIndicator, so I deactivated it. No more crash !
