### ISSUE TITLE
An example of how to configure Google Cloud would be helpful

### ISSUE THREAD

**Issue by JesperWe** [rxlabz/panache#5]
Thanks for creating this very very useful tool!

I'm trying to find how to save the resulting ThemeData, but I keep getting

`flutter: Signin error : PlatformException(missing-config, GoogleService-Info.plist file not found, null)`

even though I have added the file to the project. An example of how to configure this would be helpful.

**Comment by rxlabz** [comment]
Hi, thanks for the suggestion : I added some hints. Does it help ?

**Comment by JesperWe** [comment]
That goes a long way ;-) !
