### ISSUE TITLE
[Feature Request] This would be a great app to try hummingbird with

### ISSUE THREAD

**Issue by zurie** [rxlabz/panache#7]
This app looks like its a great app to actually use to build themes in Flutter,  super helpful.  I don't have an android so I am going to download / compile / and get it setup for iOS, but it sure would be a great project to test the Mac / PC app capabilities of flutter so you could have a companion app for when you are working on the mac / pc.

**Comment by Abacaxi-Nelson** [comment]
I agree :) +1

**Comment by rxlabz** [comment]
Done ! https://rxlabz.github.io/panache_web
